### ISSUE TITLE
First Slide open and shift to second slide then stops...

### ISSUE THREAD

**Issue by blackghostosint** [jashwant/kickass-slider#1]
maybe this answer will help others. I put the slider on http://arizonaavonrep.com . It loads, but then just sits there. I know I messed something up. (I am not the smartest bear). Is there something I missed? 

![kickass2](https://f.cloud.github.com/assets/4312279/449061/05721e80-b267-11e2-9ef6-406d36c5e15e.jpg)
![kickass1](https://f.cloud.github.com/assets/4312279/449062/057e1b86-b267-11e2-90d8-615ca40e353c.jpg)
![kickass3](https://f.cloud.github.com/assets/4312279/449063/05830934-b267-11e2-9e2e-ecf318dfad7e.jpg)

Thanks in advance

**Comment by jashwant** [comment]
@Frank-Schwarz , can you check ? Issue should be fixed by now.

**Comment by blackghostosint** [comment]
Issue is fixed. WOW. Really smooth!
