### ISSUE TITLE
Wordpress 3.6 - font settings and slides stops

### ISSUE THREAD

**Issue by rcriche** [jashwant/kickass-slider#15]
In wordpress 3.6 i can't change the font settings (type, size, color, etc.).

After the last slide the slider stops.

Your plugin is the only one that works as I need .. Please upgrade to version 3.6 of wordpress or show me how to fix these two bugs

**Comment by jashwant** [comment]
It should work with wp 3.6. I have wp 3.6 on my localhost and it works fine. Can you give me a url to your website, so that I can look ?

**Comment by rcriche** [comment]
The site is on localhost, I'm still developing.. maybe you can access it through teamviewer if you have availability

**Comment by jashwant** [comment]
Check for console errors. I don't think I'll be able to check via teamviewer. If you can upload it on server, I can look better.

**Comment by totor64** [comment]
Same problem as rcriche for the font settings with the 3.6 upgrade and later, solved by editing the z-index attribute of  wp-dialog in the editor.min.css, line 28 (was 300002, changed to 100000, and work fine now). You'll find this file in repertory wp-includes/css.
