### ISSUE TITLE
Prev / Next Arrow Dont Work

### ISSUE THREAD

**Issue by Novakinify** [jashwant/kickass-slider#16]
Everything is running smoothly except the prev / next navigation. It wont change the slides and the slides are working perfectly without prev / next navigation, how do i fix this, im thinking it can be some .js script ?

All i did was changing the height of the slider.

Thanks...

**Comment by jashwant** [comment]
Can you show the live example where I can look ?

**Comment by Novakinify** [comment]
Not right now, i will try to fix it later. Ill get back to you, thanks for the response...
