### ISSUE TITLE
Can't change Text in Slide

### ISSUE THREAD

**Issue by giopego** [jashwant/kickass-slider#18]
When I add a Text layer and try to edit it, the overlayer doesn't have the plugin TinyMce load correctly and when I save the form the console return this message:
"TypeError: tinymce.get(...) is null"
and did not save anything.
Browser: Chorme,Firefox
Wp: 3.9
Theme: All

**Comment by jashwant** [comment]
tinyMCE has been updated in 3.9. A lot of things have changed in tinyMCE. That may have broke things. I'll see it.
