### ISSUE TITLE
Navigation images? #question

### ISSUE THREAD

**Issue by Jarakeen** [jashwant/kickass-slider#2]
I am really liking this slider - it is perfect for my latest project. Thank you!

Is there a way to replace the '>'s with an image? I messed about a bit in the mustache file where the '>' live and tweaked the stylesheet, but didn't have any luck. Thank you again!

**Comment by jashwant** [comment]
@LibertysYarn ,

Go to:   `<plugin's folder>/views/mustache/slider_front_end.mustache`

You can easily replace `>` and `<` with `<img src='<url to your image'  />`.  You may also need to change (or override) css of `.prev` and `.next`

I am planning to give an option to have custom images for navigation in my next version.
But, I'll work on that when plugin download hits at least 5000 mark. Till then, enjoy and share it :+1:

**Comment by jashwant** [comment]
@LibertysYarn , you should close the issue, if your problem is fixed.
