### ISSUE TITLE
Can't change the text

### ISSUE THREAD

**Issue by cerberus478** [jashwant/kickass-slider#22]
I'm using your slider in my wordpress 4.2.2 and I can't change the text. When I "Add text" and then I get "Your text" and I double click it so that I can change it. It doesn't do anything. It doesn't save and I don't get any errors

**Comment by jashwant** [comment]
Have you tried downloading from github instead of worpdress plugin repo ?

**Comment by cerberus478** [comment]
I've tried that and that worked. Thanks
