### ISSUE TITLE
Home Slider

### ISSUE THREAD

**Issue by JessicaBrant** [jashwant/kickass-slider#3]
I love Love your slider.... but i am trying to add it to my home page an I don't see where I can do that. I am using wordpress with the twenty eleven theme... 

how do i replace there header banner with you kickass slider???

As there is no home page to add the short code..

**Comment by jashwant** [comment]
Thanks @JessicaBrant, 

If you want to place it on header area, you need to dig up your `header.php`. 

Open `header.php` in any text editor, 

Put this line `<?php echo do_shortcode('[kickass-slider id="1"]'); ?>` , where you want to show your slider (where `1` is the `id` of slider). 

Kickass generates the shortcode automatically for you. You just need to copy and paste that.

**Comment by JessicaBrant** [comment]
Jashwant,

Thank you for your timely response to this matter.. 
I have one more question for you. Where do I change the size of the sliderContainer as of now it is 584px x 400px
and I need it to be at 1000px x 288 centered....

**Comment by jashwant** [comment]
It takes the size of parent element.  Change the dimensions of parent element and you are good to go.  
You can also target the slider itself with css.

**Comment by JessicaBrant** [comment]
Loving you thanking you I will let you know how things turn out : )

**Comment by jashwant** [comment]
Sure. Do share the link to your page where you would put the slider.

And if you really want to thank me, let others know about the slider :+1:

**Comment by JessicaBrant** [comment]
I will an I intend to send you funds via paypal....

**Comment by jashwant** [comment]
Do close the issue, if it gets fixed.

You can always donate from [here](http://jashwant.github.io/kickass-slider/#donate)

**Comment by jashwant** [comment]
@JessicaBrant , do close the issue if it's fixed now.

**Comment by JessicaBrant** [comment]
Sorry for leaving this open for so long. Thanks for your help.
