### ISSUE TITLE
kickass-slider + googleapis jquery libs

### ISSUE THREAD

**Issue by foxpcteam** [jashwant/kickass-slider#4]
Hello,

how can i use googleapis jquery libs with kickass-slider?

if i add to my site jquery.min.js the kickass-slider stop working.

for example:

http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js

Thanks

**Comment by jashwant** [comment]
Try a higher version of jQuery. 

for example:

`http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js`

Do let me know if this does not fix issue.

**Comment by foxpcteam** [comment]
Hello,
i try but still not working.
have you any idea why?

Thanks

**Comment by jashwant** [comment]
May be you are including jQuery twice. Wp includes a jQuery by default in the `head`. I have tried it with google cdn jQuery and it works fine. You can share your url, so that I can look.

**Comment by jashwant** [comment]
@foxpcteam any update on this ?
