### ISSUE TITLE
Slider Problem - Shuffles! 

### ISSUE THREAD

**Issue by RobinTee** [jashwant/kickass-slider#6]
I've created more than 11 slides in one slider. 

If I add 10 slides they appear in order. Non shuffled. 

When I add 11 slides it shuffles my slides around? 

Can you help me with this issue? 

http://www.gngmagazine.co.uk

**Comment by jashwant** [comment]
Yes, there's problem in logic. I never used more than 10 slides in testing. I have found the cause of the bug. I'll fix soon (as soon as I recover from illness)

**Comment by RobinTee** [comment]
Hi Jashwant, 

I hope your feeling better.

**Comment by jashwant** [comment]
What a timing, I have pushed the fix few seconds ago. Download from
wordpress repo or github.

**Comment by RobinTee** [comment]
Hi Jashwant, 

Amazing! Where can I find the download link in Wordpress Repo or Github?

**Comment by jashwant** [comment]
This version should work

http://wordpress.org/plugins/kickass-slider/

Do let me know if this does not work.

**Comment by RobinTee** [comment]
Hi Jashwant - it still seems to shuffle the images around.

**Comment by RobinTee** [comment]
It's very peculiar. The slide numbers stay the same. However the content inside the slides shuffle.

**Comment by jashwant** [comment]
May be the wordpress repo isnt updated yet. It takes some time to propagate
among the servers.
You can download from
githubhttps://github.com/jashwant/kickass-slider/archive/master.zip

Also, clear your browser's cache. And try working on a new slide.

If problem remains there, do let me know. I am trying now with new code on
my computer, and it works for me.
- Jashwant

**Comment by RobinTee** [comment]
Dear Jashwant. I've created a new slider, installed the new plugin. Interestingly it shuffles the slides down by 1. Is there a way to delete the 'shuffle' coding? Would you like access to my site to see if you can help fix the issue?

**Comment by jashwant** [comment]
What do you mean by shuffling by 1 ? I do not shuffle the slides (in admin
panel).

**Comment by RobinTee** [comment]
Could it be another plugin that is affecting it?
