### ISSUE TITLE
Nav menu in bottom.

### ISSUE THREAD

**Issue by vol4ikman** [jashwant/kickass-slider#7]
Does it possible to add nav menu in the bottom of slider, like little thumbnails with text?
Example here: http://codecanyon.net/item/slider-pro-wordpress-premium-slider-plugin/full_screen_preview/253501

**Comment by jashwant** [comment]
KickAss does not have inbuilt options to set different types of navigation.
But, you can always create something of your own. 

KickAss provides api to navigate to `next()` , `prev()`, `goToSlide(n)`.
